function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-May-2017
%----------------------------------------------------


% Threshold image - global threshold
BW = imbinarize(X);

% Invert mask
BW = imcomplement(BW);

% Invert mask
BW = imcomplement(BW);

% Clear borders
BW = imclearborder(BW);

% Invert mask
BW = imcomplement(BW);

% Fill holes
BW = imfill(BW, 'holes');

% Fill holes
BW = imfill(BW, 'holes');

% Invert mask
BW = imcomplement(BW);

% Threshold image - global threshold
BW = imbinarize(X);

% Invert mask
BW = imcomplement(BW);

% Invert mask
BW = imcomplement(BW);

% Fill holes
BW = imfill(BW, 'holes');

% Fill holes
BW = imfill(BW, 'holes');

% Clear borders
BW = imclearborder(BW);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;